/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default']
    Back: typeof import('./src/components/Back.vue')['default']
    BackPage: typeof import('./src/components/BackPage.vue')['default']
    ChangeAnimation: typeof import('./src/components/AnimatiionCompo/ChangeAnimation.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EssayAnchor: typeof import('./src/components/EssayCompo/EssayAnchor.vue')['default']
    EssayCard: typeof import('./src/components/EssayCompo/EssayCard.vue')['default']
    GiscusComments: typeof import('./src/components/EssayCompo/GiscusComments.vue')['default']
    HeadMenu: typeof import('./src/components/HeadMenu.vue')['default']
    HobbyBreadcrumb: typeof import('./src/components/HobbiesCompo/HobbyBreadcrumb.vue')['default']
    ImageView: typeof import('./src/components/ImageView.vue')['default']
    LoadingAnimation: typeof import('./src/components/AnimatiionCompo/LoadingAnimation.vue')['default']
    NovelBreadcrumb: typeof import('./src/components/NovelBreadcrumb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAnchor: typeof import('tdesign-vue-next')['Anchor']
    TAnchorItem: typeof import('tdesign-vue-next')['AnchorItem']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TopPage: typeof import('./src/components/TopPage.vue')['default']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwiper: typeof import('tdesign-vue-next')['Swiper']
    TSwiperItem: typeof import('tdesign-vue-next')['SwiperItem']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTimeline: typeof import('tdesign-vue-next')['Timeline']
    TTimelineItem: typeof import('tdesign-vue-next')['TimelineItem']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
